# Generated by Django 4.2.1 on 2023-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
