# Generated by Django 4.2.1 on 2023-06-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_response_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
