# Generated by Django 4.2.1 on 2023-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_alter_announcement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
